### ISSUE TITLE
[bug] Every time uploading fails

### ISSUE THREAD

**Issue by SuperStarPL** [eqbeats/eqbeats#26]
![image](https://cloud.githubusercontent.com/assets/5845289/8991556/99222af8-36f9-11e5-8e53-08584277c91d.png)

Every time uploading fails, however, on the track list you have it uploaded.

**Comment by codl** [comment]
Thanks for reporting. If it still shows uploads as failed, make sure to hard-refresh the page (Ctrl + Shift + R or Command + Shift + R) before you try again.
