### ISSUE TITLE
Metadata is still wrong

### ISSUE THREAD

**Issue by SuperStarPL** [eqbeats/eqbeats#27]
![image](https://cloud.githubusercontent.com/assets/5845289/8997005/1bb11bbe-371d-11e5-9027-b258624802e2.png)

When I have long title, metadata is cut.
Also, why is it showing 0 kb/s?

**Comment by codl** [comment]
Input #0, mp3, from 'https://eqbeats.org/track/9215/mp3':
      Metadata:
        encoder         : Lavf56.25.101
        title           : Team Fortress 2 - RocketJump Waltz (LegionBeat Remix)
        artist          : LegionBeat
      Duration: 00:05:11.04, start: 0.025057, bitrate: 238 kb/s
        Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 238 kb/s

It looks fine here. Looks like this might be an issue with Windows Explorer, did you try opening the file in VLC or Winamp or some other media player? I don't have a Windows virtual machine on hand right now to test this.

**Comment by codl** [comment]
Also, re: 0 kb/s, my guess is that Explorer is unable to guess the bitrate of mp3 files with variable bitrate (the kind that EqBeats creates.)

**Comment by SuperStarPL** [comment]
I've opened that in a few media players, I don't know why its not working in Explorer. But everything is fine in VLC. Sorry for that. The issue is in Windows I think.

**Comment by codl** [comment]
I've experimented with this, and it looks like editing the tags in VLC and other programs always results in truncated tags in Explorer. I'm going to assume that if VLC didn't figure it out, there's no way I will.

I'll close this issue now. Feel free to reopen it if you find out more.
